import {
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdNotificationsNone,
  MdNotifications,
  MdMenu,
  MdCheck,
  MdFileDownload,
  MdFileUpload,
  MdEdit,
  MdFolder,
  MdHome,
  MdImage,
  MdInfo,
  MdInfoOutline,
  MdMailOutline,
  MdMail,
  MdLockOpen,
  MdLockOutline,
  MdLocationOn,
  MdPowerSettingsNew,
  MdContentCopy,
  MdPhone,
  MdLoop,
  MdRefresh,
  MdSearch,
  MdSettings,
  MdStarHalf,
  MdStarBorder,
  MdStar,
  MdDelete,
  MdPerson,
  MdPersonOutline,
  MdWarning,
  MdClose,
} from "react-icons/md";

export const Icons = {
  ArrowDown: MdKeyboardArrowDown,
  ArrowLeft: MdKeyboardArrowLeft,
  ArrowRight: MdKeyboardArrowRight,
  ArrowUp: MdKeyboardArrowUp,
  BellOutline: MdNotificationsNone,
  Bell: MdNotifications,
  Menu: MdMenu,
  Check: MdCheck,
  Close: MdClose,
  Download: MdFileDownload,
  Edit: MdEdit,
  Folder: MdFolder,
  Home: MdHome,
  Image: MdImage,
  Info: MdInfo,
  InfoOutline: MdInfoOutline,
  Mail: MdMail,
  MailOutline: MdMailOutline,
  Lock: MdLockOutline,
  LockOpen: MdLockOpen,
  LocationMarker: MdLocationOn,
  Power: MdPowerSettingsNew,
  Copy: MdContentCopy,
  Phone: MdPhone,
  Loop: MdLoop,
  Refresh: MdRefresh,
  Search: MdSearch,
  Settings: MdSettings,
  StarHalf: MdStarHalf,
  StarOutline: MdStarBorder,
  Star: MdStar,
  Delete: MdDelete,
  Upload: MdFileUpload,
  Person: MdPerson,
  PersonOutline: MdPersonOutline,
  Warning: MdWarning,
};
